# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30e660cbce33aa03087523fbe67961c5439117df3ac77ff29f00722483bccf6e25a3b3010ab7ce598441f5655d236a5bbd67d494d9f1db26921ae3991b84a317

test:
  secret_key_base: a1b5f43a831e61847d9acead20b32a816df742ba0c5d76c67d97ff431bb3128e367de7ae127cac9b15ede681405d47df3b8e18f257bac337c5fd3c00d3935803

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
